
package vis.greece.makemyplan.salesorderbackend.schema.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * A lead is the identification of an individual or organisation (Party) that has the interest and authority to purchase a product or service. This represents the first stage of a sales process. The identification of the lead is referred to as Lead Generation, a process conducted by either the marketing or sales organization. Thus, the Lead Entity in CIM is generated by the Lead Generation Interaction. This is a Party Interaction. The lead may have an organisation associated (an Enterprise Sales Lead) with the individual(s). For potential Enterprise Customers, The lead is considered to be a role of Organisation since the Lead individual will not become a customer per se. The individual represents the company (Legal Entity) with which Vodafone hope to do business.
 * 
 * <p>Java class for SalesLeadReferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SalesLeadReferenceType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://group.vodafone.com/schema/common/v1}BaseComponentType">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SalesLeadReferenceType")
public class SalesLeadReferenceType
    extends BaseComponentType
{


}
