package vis.greece.makemyplan.model;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ComboBundles", targetNamespace = "http://osb.vodafone.com/gr/ComboBundles", wsdlLocation = "file:/C:/Users/USER/Desktop/AmirWSDL/wsdl.wsdl")
public class ComboBundles
    extends Service
{

    private final static URL COMBOBUNDLES_WSDL_LOCATION;
    private final static WebServiceException COMBOBUNDLES_EXCEPTION;
    private final static QName COMBOBUNDLES_QNAME = new QName("http://osb.vodafone.com/gr/ComboBundles", "ComboBundles");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/USER/Desktop/AmirWSDL/wsdl.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMBOBUNDLES_WSDL_LOCATION = url;
        COMBOBUNDLES_EXCEPTION = e;
    }

    public ComboBundles() {
        super(__getWsdlLocation(), COMBOBUNDLES_QNAME);
    }

    public ComboBundles(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMBOBUNDLES_QNAME, features);
    }

    public ComboBundles(URL wsdlLocation) {
        super(wsdlLocation, COMBOBUNDLES_QNAME);
    }

    public ComboBundles(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMBOBUNDLES_QNAME, features);
    }

    public ComboBundles(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ComboBundles(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ComboBundlesPortType
     */
    @WebEndpoint(name = "ComboBundlesSOAPPort")
    public ComboBundlesPortType getComboBundlesSOAPPort() {
        return super.getPort(new QName("http://osb.vodafone.com/gr/ComboBundles", "ComboBundlesSOAPPort"), ComboBundlesPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ComboBundlesPortType
     */
    @WebEndpoint(name = "ComboBundlesSOAPPort")
    public ComboBundlesPortType getComboBundlesSOAPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://osb.vodafone.com/gr/ComboBundles", "ComboBundlesSOAPPort"), ComboBundlesPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMBOBUNDLES_EXCEPTION!= null) {
            throw COMBOBUNDLES_EXCEPTION;
        }
        return COMBOBUNDLES_WSDL_LOCATION;
    }

}
