package vis.greece.makemyplan.model;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ComboBundlesPortType", targetNamespace = "http://osb.vodafone.com/gr/ComboBundles")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ComboBundlesPortType {


    /**
     * 
     * @param bundleCode
     * @param channel
     * @param msisdn
     * @return
     *     returns test.BackResult
     */
    @WebMethod(action = "http://osb.vodafone.com/gr/ComboBundles/activateBundle")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "activateBundle", targetNamespace = "http://osb.vodafone.com/gr/ComboBundles", className = "test.ActivateBundle")
    @ResponseWrapper(localName = "activateBundleResponse", targetNamespace = "http://osb.vodafone.com/gr/ComboBundles", className = "test.ActivateBundleResponse")
    public BackResult activateBundle(
        @WebParam(name = "msisdn", targetNamespace = "")
        String msisdn,
        @WebParam(name = "bundleCode", targetNamespace = "")
        List<String> bundleCode,
        @WebParam(name = "channel", targetNamespace = "")
        String channel);

    /**
     * 
     * @param service
     * @param channel
     * @param msisdn
     * @param type
     * @return
     *     returns test.BackResult
     */
    @WebMethod(action = "http://osb.vodafone.com/gr/ComboBundles/register")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://osb.vodafone.com/gr/ComboBundles", className = "test.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://osb.vodafone.com/gr/ComboBundles", className = "test.RegisterResponse")
    public BackResult register(
        @WebParam(name = "msisdn", targetNamespace = "")
        String msisdn,
        @WebParam(name = "service", targetNamespace = "")
        String service,
        @WebParam(name = "channel", targetNamespace = "")
        String channel,
        @WebParam(name = "type", targetNamespace = "")
        String type);

    /**
     * 
     * @param service
     * @param channel
     * @param msisdn
     * @param type
     * @return
     *     returns test.BackResult
     */
    @WebMethod(action = "http://osb.vodafone.com/gr/ComboBundles/unregister")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unregister", targetNamespace = "http://osb.vodafone.com/gr/ComboBundles", className = "test.Unregister")
    @ResponseWrapper(localName = "unregisterResponse", targetNamespace = "http://osb.vodafone.com/gr/ComboBundles", className = "test.UnregisterResponse")
    public BackResult unregister(
        @WebParam(name = "msisdn", targetNamespace = "")
        String msisdn,
        @WebParam(name = "service", targetNamespace = "")
        String service,
        @WebParam(name = "channel", targetNamespace = "")
        String channel,
        @WebParam(name = "type", targetNamespace = "")
        String type);

}
