swagger: '2.0'
info:
  description: Sales Order API Documentation
  version: '1.0'
  title: Sales Order API Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8006'
basePath: /
tags:
  - name: sales-order-controller
    description: Sales Order Controller
paths:
  /gr/v1/sales/order:
    post:
      tags:
        - sales-order-controller
      summary: manipulateBundles
      operationId: manipulateBundlesUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - 
          name: "Authorization"
          in: "header"
          description: "Enables the developer application access to the request resource. Contains the JWT OAuth token as Bearer token"
          required: true
          type: "string"
        - in: body
          name: salesOrderDto
          description: salesOrderDto for manipulating (Add, Update, delete) the Addons for specific Assets [MSISDNs]
          required: true
          schema:
            $ref: '#/definitions/SalesOrderDto'
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
definitions:
  ProductOffer:
    type: object
    properties:
      action:
        type: string
        enum:
          - ADD
          - DELETE
          - UPDATE
      integrationId:
        type: string
      name:
        type: string
      oldThreshold:
        type: integer
      newThreshold:
        type: integer
        
  Addon:
    type: object
    properties:
      description:
        type: string
        enum:
          - CONNECTION
      msisdn:
        type: string
      priority:
        type: integer
        format: int32
      productOffers:
        type: array
        items:
          $ref: '#/definitions/ProductOffer'
  SalesOrderDto:
    type: object
    properties:
      addons:
        type: array
        items:
          $ref: '#/definitions/Addon'
      channelType:
        type: string
      orderSubType:
        type: string
      orderType:
        type: string
      source:
        type: string
      version:
        type: string
  ModelAndView:
    type: object
    properties:
      empty:
        type: boolean
      model:
        type: object
      modelMap:
        type: object
        additionalProperties:
          type: object
      reference:
        type: boolean
      status:
        type: string
        enum:
          - '100'
          - '101'
          - '102'
          - '103'
          - '200'
          - '201'
          - '202'
          - '203'
          - '204'
          - '205'
          - '206'
          - '207'
          - '208'
          - '226'
          - '300'
          - '301'
          - '302'
          - '303'
          - '304'
          - '305'
          - '307'
          - '308'
          - '400'
          - '401'
          - '402'
          - '403'
          - '404'
          - '405'
          - '406'
          - '407'
          - '408'
          - '409'
          - '410'
          - '411'
          - '412'
          - '413'
          - '414'
          - '415'
          - '416'
          - '417'
          - '418'
          - '419'
          - '420'
          - '421'
          - '422'
          - '423'
          - '424'
          - '426'
          - '428'
          - '429'
          - '431'
          - '451'
          - '500'
          - '501'
          - '502'
          - '503'
          - '504'
          - '505'
          - '506'
          - '507'
          - '508'
          - '509'
          - '510'
          - '511'
      view:
        $ref: '#/definitions/View'
      viewName:
        type: string
  View:
    type: object
    properties:
      contentType:
        type: string
